pipeline:
  name: DeployToFargate
  identifier: DeployToFargate
  projectIdentifier: default_project
  orgIdentifier: default
  description: Deploy Docker image from JFrog to AWS Fargate
  tags: {}
  stages:
    - stage:
        name: DeployToFargate
        identifier: DeployToFargate
        description: Provision AWS resources using CloudFormation
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: AWSProvisioner
                    configuration:
                      stackName: HTMLStake
                      connectorRef: AWS
                      region: us-east-1
                      templateFile:
                        type: Inline
                        spec:
                          templateBody: |
                            Resources:
                              # IAM Role for Fargate Tasks
                              FargateTaskExecutionRole:
                                Type: 'AWS::IAM::Role'
                                Properties:
                                  AssumeRolePolicyDocument:
                                    Version: '2012-10-17'
                                    Statement:
                                      - Effect: 'Allow'
                                        Principal:
                                          Service: 'ecs-tasks.amazonaws.com'
                                        Action: 'sts:AssumeRole'
                                  ManagedPolicyArns:
                                    - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

                              # ECS Cluster
                              MyEcsCluster:
                                Type: 'AWS::ECS::Cluster'
                                Properties:
                                  ClusterName: my-fargate-cluster

                              # ECS Task Definition
                              MyTaskDefinition:
                                Type: 'AWS::ECS::TaskDefinition'
                                Properties:
                                  Family: 'my-fargate-task'
                                  NetworkMode: 'awsvpc'
                                  RequiresCompatibilities:
                                    - FARGATE
                                  Cpu: '256'
                                  Memory: '512'
                                  ExecutionRoleArn: !GetAtt FargateTaskExecutionRole.Arn
                                  ContainerDefinitions:
                                    - Name: 'my-app-container'
                                      Image: 'trialvj.jfrog.io/docker-html-local/my-html-app:latest'
                                      Cpu: 256
                                      Memory: 512
                                      PortMappings:
                                        - ContainerPort: 80
                                          HostPort: 80
                      roleArn: ""
                  timeout: 10m
