pipeline:
  name: HTML-Deployment-Pipeline
  identifier: HTMLDeploymentPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  description: Pipeline to demonstrate deployment of simple html page to AWS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: HTML
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build_and_Push_Image
                  identifier: Build_and_Push_Image
                  spec:
                    shell: Sh
                    command: |-
                      # Set strict error handling (exit script on any non-zero exit code)
                      set -e

                      # Construct the semantic version from stage variables
                      VERSION=<+stage.variables.get("MAJOR_VERSION")>.<+stage.variables.get("MINOR_VERSION")>.<+stage.variables.get("PATCH_VERSION")>
                      # Build the Docker image with the semantic version tag
                      docker build -t my-html-app:$VERSION .

                      # Retrieve JFrog credentials from secrets manager
                      JFROG_USERNAME=<+secrets.getValue("jFrog")>
                      JFROG_PASSWORD=<+secrets.getValue("jfrogPass")>
                      ARTIFACTORY_TOKEN=<+secrets.getValue("ARTIFACTORY_TOKEN")>

                      # Login to JFrog Artifactory using a secret token (avoid storing username/password in plain text)
                      echo "$ARTIFACTORY_TOKEN" | docker login trialvj.jfrog.io --username vjdevops@hotmail.com --password-stdin

                      # Tag the built image for pushing to JFrog Artifactory
                      docker tag my-html-app:$VERSION trialvj.jfrog.io/docker-html-local/my-html-app:$VERSION

                      # Push the image to JFrog Artifactory repository
                      docker push trialvj.jfrog.io/docker-html-local/my-html-app:$VERSION
                  description: Build and push docker image to jFrog Artifactory
        variables:
          - name: MAJOR_VERSION
            type: String
            description: ""
            required: false
            value: "1"
          - name: MINOR_VERSION
            type: String
            description: ""
            required: false
            value: "0"
          - name: PATCH_VERSION
            type: String
            description: ""
            required: false
            value: "0"
