pipeline:
  name: HTML-Deployment-Pipeline
  identifier: HTMLDeploymentPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  description: Pipeline to demonstrate deployment of simple html page to AWS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: HTML
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPush-jFrog-DockerRegistry_1
                  identifier: BuildAndPushjFrogDockerRegistry_1
                  spec:
                    connectorRef: Jfrog_Docker_Registry
                    repo: docker-html-local
                    tags:
                      - latest
                    caching: true
                    dockerfile: Dockerfile
