Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-cluster

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: html-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: html-container
          Image: html-docker-image:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-f6d7698f0004cac6d  # Updated with a valid subnet ID
          SecurityGroups:
            - sg-383899427715f9a6a
          AssignPublicIp: ENABLED

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: vpc-d0e099ff834ed8ec5  # Specify the VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  EcsServiceUrl:
    Description: "URL of the ECS Service"
    Value: !Sub "http://${MyService}.localhost.localstack.cloud"
