Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-cluster

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: html-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: html-container
          Image: html-docker-image:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-563a1fa2b8c77a4db
          SecurityGroups:
            - sg-383899427715f9a6a
          AssignPublicIp: ENABLED

Outputs:
  EcsServiceUrl:
    Description: "URL of the ECS Service"
    Value: "http://localhost:80"
